aula/index.html

Adicionando o nome e link da Thaysa Gomes

Aula thaysagomes

---

aula/index.html

Adicionado o username e o link de Amanda Rebeca

Aula amanda

---

aula/index.html

Adicionado o username e o link da Patricia Pereira

Aula patriciapereira

---

aula/index.html

Adicionado o link e o username de Taline joventino

Aula taline

---

aula/index.html

Adicionado o username e o link da Lohany Formiga

Aula lohanyformiga

---

aula/index.html

Adicionado o username e o link da Beatriz Liu

Aula beatriz

---

aula/index.html
projeto/index.html

Adicionando o username e o link do github

Aula danielly

---

aula/index.html

Adicionado o username e link da Anna Beatriz

Aula annabeatriz

---

aula/index.html

Adicionadado o Username e o Link da Jéssica Rayanne Guerra

Aula jessica

---

aula/index.html

Adicionado o username  e o link da Adrielly Santos

Aula adrielly

---

aula/index.html

Adicionado o username e o link da Samanta Silva

Aula samantasilva

---

aula/index.html

Adicionado o username e o link de Janaina Santina.

Aula janainasantina

---

aula/index.html

Adicionados username e link da Ana Luiza

Aula analuiza

---

aula/index.html

Adicionado o username e o link do perfil no Github da Sabrina Mares

Aula sabrina

---

aula/index.html

Adicionado o username e o link da Darlene.

Aula darlene

---

aula/index.html

Adicionado o usernamne e o link da Aline

Aula aline

---

aula/index.html

Adicionado o username e o link da Ana Ambrósio

Aula anaambrosio

---

aula/index.html

Adicionado o username e o link da Marta Santos

Aula martasantos

---

aula/index.html

Adicionado o username e o link de Dani Bezerra.

Aula danibezerra

---

aula/index.html

Adicionado username e o link da Deliany Cristina

Aula delianycristina

---

aula/index.html

Adicionado o username e o link de SanmarahM

Aula sanmarah

---

aula/index.html

Adicionado o username e o link da Viviane Santos

Aula vivianesantos

---

projeto/index.html

foto de perfil e link para repo de Darlene

feat(github): foto de perfil e link para repo de Darlene:

---

aula/index.html
projeto/index.html

Proj lohanyformiga

---

aula/index.html

Adicionado o user name e link da Michele Coelho.

Aula michelecoelho

---

projeto/index.html

feat(github) : foto de perfil e link para repo de Cintia Fumi

---

aula/index.html
projeto/index.html

Foto de perfil e link para repo de Viviane Santos

feat(github): foto de perfil e link para repo de Viviane Santos

---

projeto/index.html

Atualização da foto e link do github

feat(fernandaraiza): foto de perfil e link para repo de Fernanda Raiza

---

aula/index.html

Add o link do git e fazendo as mudanças

Aula biamichelle

---

revisao/index.html

feat(GIF): Adicionado git fav Aline

---

revisao/index.html

feat(gif): adicionado gif favorito

---

projeto/index.html

Alteração no index para colocar minha foto de perfil e o link do meu repositório!

feat(github): foto de perfil e link para repo de Adrielly Silva

---

projeto/index.html

feat(github): Atualização foto do perfil e link para repo de Taline joventino

---

projeto/index.html
revisao/index.html

Revisao sara
